### ISSUE TITLE
Make the geoserver container populate the datadir at runtime

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-docker#57]
This task want to solve two issues at the same time:

1. get rid of the `geoserver_data` image and container, whose single purpose is to bake the content of the datadir volume
2. populate the datadir content at runtime instead of build time. This is required to allow bind mounting the datadirectory, instead of relying on Docker's internal volume. Explanation: the VOLUME directive inside the geoserver_data dir + the copying of content at build time forces the creation of an internal volume (that is shared with the `geoserver` image). If a bind mount is configured inside the Docker Compose configuration, it will be empty, since inside the container it's shadowed by the Docker volume. By moving the copy of datadir content at runtime we ensure that either the internal volume or a bind mounted volume is populated the first time the container is run.

**Comment by ridoo** [comment]
Related: https://github.com/GeoNode/geonode-docker/issues/38

**Comment by giohappy** [comment]
>Related: https://github.com/GeoNode/geonode-docker/issues/38

@ridoo what's your feedback on this PR?

**Comment by ridoo** [comment]
hey @giohappy .. had a quick look. Here are my 2cts:

* Either use `curl` or `wget` .. AFAIK `curl` is pre-installed more often
* `data_dir` from `geonode-geoserver-ext` could be part of this repository -- even better: keep only those which are relevant to GeoNode 
* In the `Dockerfile` copy the GeoNode specific files to the appropriate locations

Once done, the default `data_dir` is part of the image but volatile in a created container. However, users want to persist the data dir of course. The docker-compose setup has to reference that data dir as shared volume, like so:

**`compose.yml`**
```
services:                                                                                                                                                             
     my-service:
       image: hello-world:latest
       volumes:
         - my-shared-volume:/etc
   
   volumes:
     my-shared-volume:
```

The volume is created and populated [for the first time running the container](https://docs.docker.com/engine/storage/volumes/#use-a-volume-with-docker-compose) and available under the host's `/var/lib/docker/volumes` by default. It can be configured to be stored elsewhere of course (see [the NFS example](https://docs.docker.com/reference/compose-file/volumes/#driver_opts) in the reference docs).

With this

* The `data_dir` is versioned and is located where it is actually used
* No extra repository needed
* Reduced complexity in creating the image
